server:
  port: 80
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/javat?useSSL=false&serverTimezone=UTC
      username: root
      password: kokoro

mybatis-plus:
  global-config:
    db-config:
      table-prefix: tbl_
      id-type: auto
  configuration:
    # ?? MP ????, ???? sout ???
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
